site_name: ISOFIT
site_url: https://isofit.github.io/isofit/
repo_name: isofit/isofit
repo_url: https://github.com/isofit/isofit/
docs_dir: docs/
# theme:
#   name: readthedocs
theme:
  name: material
  theme:
  palette:
    # Palette toggle for automatic mode (light during day, dark during night)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
plugins:
  - search
  - mkapi
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      baselevel: 2
extra_css:
  - stylesheets/icons.css
extra:
  version:
    provider: mike
nav:
  - Getting Started:
    - Installation: getting_started/installation.md
    - Quick Start (New Users): getting_started/quickstarts/srtmnet.md
    - MODTRAN: getting_started/quickstarts/modtran.md
    - Best Practices: getting_started/best_practices.md
  - Extra Downloads:
    - Dependencies: extra_downloads/data.md
    - Building Examples: extra_downloads/building_examples.md
  - Tutorials: https://isofit.github.io/isofit-tutorials
  - Docker: docker.md
  - Information:
    - Bibliography: information/bibliography.md
    - Code of Conduct: information/code_of_conduct.md
  - Developers:
    - Contributing: developers/contributing.md
    - Documentation: developers/documentation.md
    - Testing: developers/testing.md
  # - Reference:
  #   - $api/isofit.***
