site_name: ISOFIT
repo_name: isofit/isofit
repo_url: https://github.com/isofit/isofit
docs_dir: docs/
theme:
  name: readthedocs
plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Getting Started:
    - About: about
    - Installation: installation
    - Quick Start (New Users): installation#quick-start-with-srtmnet-recommended-for-new-users
    - Data: data
    - Extra Downloads: data#extra-downloads
    - Configuration Options: data#configuration-options
    - Downloads: data#downloads
    - Developers: data#developers
    - Best Practices: best_practices
  - Tutorials: https://isofit.github.io/isofit-tutorials
  - Docker:
    - Tags: docker
    - Getting Started: docker#getting-started
    - Jupyter: docker#jupyter
    - Slim: docker#slim
  - Information:
    - Bibliography: bibliography
    - Code of Conduct: code_of_conduct
  - Developers:
    - Contributing: CONTRIBUTING
    - Documentation: documentation
    - Profiling: profiling
  - API:
    - API Reference: https://isofit.readthedocs.io/en/latest/autoapi/index#
